"""Alembic configuration."""
from alembic import config as alembic_config
import os

class Config:
    """Alembic config."""
    
    def __init__(self):
        self.config = alembic_config.Config("alembic.ini")
        self.config.set_main_option(
            "sqlalchemy.url",
            os.environ.get("DATABASE_URL", "postgresql://localhost/ghost_investor_ai"),
        )

config = Config().config
